# Generated by Django 4.2.1 on 2023-06-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='visibilidade',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=15),
        ),
    ]
