# Generated by Django 4.2.2 on 2023-06-18 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_alter_publicacao_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Curtidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_curtida', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_usuario', to='chat.publicacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
