# Generated by Django 4.2.2 on 2023-06-19 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0010_comentario_curtida_delete_comentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='comentarios',
            field=models.ManyToManyField(blank=True, related_name='publicacoes', to='chat.comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='chat.publicacao'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to=settings.AUTH_USER_MODEL),
        ),
    ]
